### ISSUE TITLE
Can't build with latest k6 due to incompatibility with grpc lib

### ISSUE THREAD

**Issue by mstoykov** [grafana/xk6-loki#39]
K6 did update to the latest (at the time gRPC) release and I just found out that this extensions doesn't build with that due to https://github.com/weaveworks/common/pull/240 . 

I am wondering if somebody on the loki team can not look into testing this and maybe get this PR merged :crossed_fingers: 

I don't know if loki updates gRPC lib regularly but that will block them as well :(

**Comment by chaudum** [comment]
Loki uses `google.golang.org/grcp v1.45.0`, whereas this `weaveworks/common` PR updates to `v1.34.0`.

https://github.com/grafana/loki/blob/a1c72ad562229cbd5d9fcd0e1075f3e80a6a3745/go.mod#L328-L329

https://github.com/weaveworks/common/pull/240/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R37

**Comment by mstoykov** [comment]
I kind of hoped that we can push this to be merged upstream so that we don't have to replace the gRPC version :grimacing:
