### ISSUE TITLE
Can't build with xk6

### ISSUE THREAD

**Issue by KurzweilTV** [grafana/xk6-loki#55]
If you try to build this with `xk6 build --with github.com/grafana/xk6-loki`, like most tutorials online suggest it will fail, which blocks from installing more than one plugin with `xk6-loki`

For example, if I wanted to test Loki, and then remote write the results to prometheus.

**Comment by marcusteixeira** [comment]
Error msg???

**Comment by javaducky** [comment]
@KurzweilTV it would appear there are some known dependency issues (I don't know the exact details) when building the k6 using xk6-loki based upon the current [Makefile](https://github.com/grafana/xk6-loki/blob/main/Makefile#L7-L12).

I was able to confirm that `xk6 build --with github.com/grafana/xk6-loki` will fail as you mentioned, however including the `--replace` options based on the Makefile, will allow build. Below is the updated command line that works:

```
xk6 build master \
 --replace "github.com/mingrammer/flog=github.com/chaudum/flog@v0.4.4-0.20220419113107-eb2f67f18b99" \
 --replace "google.golang.org/grpc=google.golang.org/grpc@v1.45.0" \
 --replace "github.com/hashicorp/consul=github.com/hashicorp/consul@v1.5.1" \
 --replace "github.com/go-kit/log=github.com/dannykopping/go-kit-log@v0.2.2-0.20221002180827-5591c1641b6b" \
 --with github.com/grafana/xk6-loki
```
Advise to use the modified build command until the dependency issues can be addressed by the maintainers.
