### ISSUE TITLE
Missing released versions

### ISSUE THREAD

**Issue by szkiba** [grafana/xk6-loki#68]
This is a polite warning that the extension does not meet the k6 extension registry [requirements](https://grafana.com/docs/k6/latest/extensions/explanations/extensions-registry/)

Currently, the extension does not have a versioned release that meets the requirements.

As stated in the [About the Extensions Registry](https://grafana.com/docs/k6/latest/extensions/explanations/extensions-registry/) document, extensions that do not meet the registry's requirements will be de-listed.

An automatic system will be implemented soon, which checks whether the registered extensions meet the requirements and automatically de-lists the extensions that do not.

Of course, you can re-register the de-listed extension later, but in order to avoid inconvenience, it is advisable to meet the requirements.

**Comment by szkiba** [comment]
Hi @chaudum , @na-- , @vlad-diachenko,

Just a ping. Could you please find some time for this in the near future?

**Comment by vlad-diachenko** [comment]
Hey @szkiba . 
I am not sure if this extension is widely used nowadays... 
But, anyway, I manually created [v1.0.0 release ](https://github.com/grafana/xk6-loki/releases/tag/v1.0.0). Is it enough to meet the requirements?

**Comment by szkiba** [comment]
Hey @vlad-diachenko, Thanks, it's perfect.
